name: Frontend checks

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  Formatting check:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: Clean install dependencies
        working-directory: ./frontend
        run: npm ci
      - name: Check formatting
        working-directory: ./frontend
        run: npm run format-check

